### ISSUE TITLE
Installtion instructions with Pkg.add according to Readme

### ISSUE THREAD

**Issue by TheWisator** [Smolkaa/MyMakieThemes.jl#1]
Using the recommended installation procedure on Julia 1.8.5 gives the following error:
```
julia> Pkg.add("https://github.com/Smolkaa/MyMakieThemes.jl.git")
ERROR: `https://github.com/Smolkaa/MyMakieThemes.jl.git` is not a valid package name
The argument appears to be a URL or path, perhaps you meant `Pkg.add(url="...")` or `Pkg.add(path="...")`.
```
Suggested correction with "url=..." acc. to the Pgk.jl API reference: https://pkgdocs.julialang.org/v1/api/#Pkg.add 
`Pkg.add(url="https://github.com/Smolkaa/MyMakieThemes.jl.git")`

**Comment by Smolkaa** [comment]
You're totally right, the `README` has been adapted!
